data:
  data_path: ./data
  image_size: 768
  images_folder: images
  masks_folder: masks
  num_classes: 13
  train_ratio: 0.8
device: cuda
experiment_name: large_maskrcnn_r101
model:
  batch_size_per_image: 512
  model_name: mask_rcnn_R_101_FPN_3x
  name: Mask R-CNN R101-FPN
  num_classes: 13
  num_gpus: 1
output_dir: ./outputs
seed: 42
training:
  batch_size: 2
  checkpoint_period: 500
  learning_rate: 0.01
  lr_decay_gamma: 0.1
  lr_decay_milestones:
  - 7500
  - 11250
  max_iter: 15000
  momentum: 0.9
  num_workers: 4
  patience: 15
  warmup_iters: 1000
  weight_decay: 0.0001
